# site title
title = "r4rnaseq"

# site name
site_name = "R for RNA-Seq Anlaysis Examples"

# where site will be served from
site_url = "http://raynamharris.com/r4rnaseq/"

# the github repository from which to pull the issues:
github_repo = "raynamharris/r4rnaseq"

# site-specific templates (MORE HERE)
add_pages = [ "index.md", "examples.md", "labels.md" ]

# username on github (if you want to use authentication with the API; leave empty if not)
github_username = 'raynamharris'

# local output file to which to pull issues.
issues_dump = 'r4rnaseq.dmp'
